server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

kakaopay:
  secret-key: ${KAKAOPAY_KEY}
  cid: ${KAKAOPAY_CID}
  ready-url: ${KAKAOPAY_READY_URL}
  approve-url: ${KAKAOPAY_APPROVE_URL}