server:
  port: 8080

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  profiles:
    include: oauth

kakaopay:
  secret-key: ${KAKAOPAY_KEY}
  cid: ${KAKAOPAY_CID}
  ready-url: ${KAKAOPAY_READY_URL}
  approve-url: ${KAKAOPAY_APPROVE_URL}
  cancel-url: ${KAKAOPAY_CANCEL_URL}

cloud:
  aws:
    s3:
      bucket: catchstudy
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
